version: '3.7'

services:
  app:
    build: .
    image: avas-cash
    container_name: avas-cash
    restart: always
    ports:
      - '127.0.0.1:5000:3000'   # use with proxy server (eg. Nginx)
      # - '0.0.0.0:80:3000'     # use without proxy server
